fix failure in return-type-change integration test
This test looks like it has always failed when run on Java 11, but we
did not notice for a while because the CI pipeline was not running any
of these tests (#130).

The cause seems to be that the NoSuchMethodError getMessage() return
value has changed.